### ISSUE TITLE
Can't login. Error 33804.

### ISSUE THREAD

**Issue by jupiler5** [cxii-dev/script.tvshowtime#71]
Hi everyone,

Over the past few days, I can't login to TVShow Time. 
Each time I click on "Login" a get immediately "Error 33804" message.

I tried with Kodi 18.3 and 17.6. With my smartphone, my laptop, 2 different tablets and my Minix. Always the same issue...

Any idea?

Many thanks in advance for your help !

**Comment by enrique131** [comment]
Hi,
Had the same issue:
1) Delete the addon
2) Install the addon from https://github.com/cxii-dev/script.tvtime
3) Log again.
4) activate following indication on the kodi.
It is working for me. 
Hope it also works for you

**Comment by jupiler5** [comment]
Thank you, Enrique, for your help!

I tried and... it works!

The version available on GitHub is v1.2, against v1.1.2 on the official Kodi add-on repository.
It seems v1.1.2 (still branded as "TVShow Time", against "TV Time" for v1.2) doesn’t work anymore.

**Comment by jupiler5** [comment]
Update.
First, I downloaded v1.2 from https://github.com/cxii-dev/script.tvtime.
With this version, I can connect but it doesn't synchronize.
I have the "Welcome notification" but no playback notification. It neither doesn't ask for my "Emotion" at the end of an episode…

Then, I downloaded the latest release (v1.2.2) by "alxlaxv" (https://github.com/alxlaxv/script.tvtime/releases) and everything works great :-)

**Comment by obygyv** [comment]
I still have the error 33804 with v1.2 or v1.2.2 (alxlaxv). Kodi 17.3
Any advice?

**Comment by jupiler5** [comment]
Sorry, no idea. Maybe try another Kodi version (17.6 or 18.3) ?
I use it with both of them and it works..

**Comment by enrique131** [comment]
> I still have the error 33804 with v1.2 or v1.2.2 (alxlaxv). Kodi 17.3
> Any advice?

I have Kodi 18.3 as well. Maybe you need the update for it to work

**Comment by obygyv** [comment]
It didn't work with 17.6, but worked with 18.0. I lost my Aenon Nox template but I could connect to TVTime. A blessing in disguise...

**Comment by rehannali** [comment]
Worked fine with kodi 18.6

**Comment by rehannali** [comment]
> Update.
> First, I downloaded v1.2 from https://github.com/cxii-dev/script.tvtime.
> With this version, I can connect but it doesn't synchronize.
> I have the "Welcome notification" but no playback notification. It neither doesn't ask for my "Emotion" at the end of an episode…
> 
> Then, I downloaded the latest release (v1.2.2) by "alxlaxv" (https://github.com/alxlaxv/script.tvtime/releases) and everything works great :-)

works fine with kodi 18.6. I use alxlaxv plugin.

**Comment by lameiraneves** [comment]
Hi everyone, I'm really struggling with this, I checked the code and everything but I didn't really understand how I should use it, could someone help me? I'm a total noob btw
Tks y'all

**Comment by eraser-head** [comment]
it's happening again

**Comment by amj87** [comment]
It's happening for me. I have kodi 18.9 version

**Comment by Arryby** [comment]
starting to encounter again the login error 33804 on Kodi Leia 18.9

**Comment by jupiler5** [comment]
This plugin is discontinued.
Last working TVTime plugin is here: https://github.com/alxlaxv/script.tvtime/
Please note that, at the moment, this plugin doesn't work anymore too.

See https://github.com/thisis-mental/script.tvtime/issues/5 for issue follow-up.

**Comment by amj87** [comment]
> This plugin is discontinued.
> Last working TVTime plugin is here: https://github.com/alxlaxv/script.tvtime/
> Please note that, at the moment, this plugin doesn't work anymore too.
> 
> See [thisis-mental#5](https://github.com/thisis-mental/script.tvtime/issues/5) for issue follow-up.

Thank you. I think this is because API site isn't working currenty, right?

**Comment by jupiler5** [comment]
Fixed and adapted to Kodi 19 (Python v3) by RSantos94 and Panizza :-)
New working script: https://github.com/RSantos94/script.tvtime

**Comment by amj87** [comment]
> Fixed and adapted to Kodi 19 (Python v3) by RSantos94 and Panizza :-)
> New working script: https://github.com/RSantos94/script.tvtime

Hi,

It worked for a while then the same error shows.

Regards,

**Comment by jupiler5** [comment]
> 
> 
> > Fixed and adapted to Kodi 19 (Python v3) by RSantos94 and Panizza :-)
> > New working script: https://github.com/RSantos94/script.tvtime
> 
> Hi,
> 
> It worked for a while then the same error shows.
> 
> Regards,

I confirm. https://api.tvtime.com/ is offline... again...

**Comment by bn326160** [comment]
Hi @jupiler5, are the API issues still present in your experience?
I got here after some googling and trying to Dockerize https://github.com/imrabti/tvshowtime-plex and try to get it to work on my server. Sorry if this is off-topic.

**Comment by jupiler5** [comment]
> 
> 
> Hi @jupiler5, are the API issues still present in your experience?
> I got here after some googling and trying to Dockerize https://github.com/imrabti/tvshowtime-plex and try to get it to work on my server. Sorry if this is off-topic.

Hi @bn326160, I confirm, TVTime API is down again...

**Comment by enrique131** [comment]
The API being down is becoming usual.... somebody knows more about it? Does it takes weeks, months? I checked the tvtime twitter but there is no mentioned about it. I'm just wondering about when or If it will go back to normal

**Comment by batkins2** [comment]
I've just received an email from the TVTime staff. They are shutting down the public API, permanently.

**Comment by amj87** [comment]
I receive the same they will terminate it.

**Comment by jupiler5** [comment]
+1. Same mail...

**Comment by enrique131** [comment]
That is a pity. The main thing for me was that it synced with kodi to keep all tied together. 
Anyone can think about an alternative besides trakt.tv? The android app takes around 5 minutes to sync when i open it

**Comment by obygyv** [comment]
This guy made a solution "API-free", he says it works but it's only for Plex now. Maybe someone can make it for Kodi? It deserves more visibility.
https://github.com/Kwbmm/scraped-tvtime-api

**Comment by TheSarge81AN** [comment]
It's happening again, I receive the 33804 error on login

**Comment by jupiler5** [comment]
> 
> 
> It's happening again, I receive the 33804 error on login

Has said above, TVTime shut down definitely its API. So it won't work anymore...
